In [1]:
import numpy as np

In [2]:
training_inputs = np.array([[1, -2, 0, -1], [0, 1.5, -0.5, -1], [-1, 1, 0.5, -1]])
weights = np.array([1, -1, 0, 0.5])  #np.random.rand(x, no. of columns)for decimal numbers(no -ve)
d = np.array([-1, -1, 1])            #np.random.randint(-x, x, no. of colums)for integers
print('Training Inputs:\n', training_inputs)
print('Initial weights:\n', weights)
print('d:\n', d)

Training Inputs:
 [[ 1.  -2.   0.  -1. ]
 [ 0.   1.5 -0.5 -1. ]
 [-1.   1.   0.5 -1. ]]
Initial weights:
 [ 1.  -1.   0.   0.5]
d:
 [-1 -1  1]


In [4]:
def bipolar_sigmoid(net):
    return round((1 - np.exp(-net)) / (1 + np.exp(-net)), 3)

def fnet_(x):#for bipolar_sigmoid          #for unipolar_sigmoid x(1-x)
    return round(((1 - x ** 2) / 2), 3)


In [5]:
c = 0.1
for count in range(5000): #trained 500 times
    for i in range(len(training_inputs)): #0r do enumerate or zip from iterablemodule😉
        fnet = bipolar_sigmoid(np.dot(training_inputs[i], weights))
        fnet__ = fnet_(fnet)
        del_w = c * fnet__ * np.dot(training_inputs[i],d[i]-fnet)
        weights += del_w
    print(f'ITERATION {count + 1}:', weights)

ITERATION 1: [ 0.9474045  -0.9296748   0.01607585  0.5045767 ]
ITERATION 2: [ 0.8878911  -0.8497524   0.03403005  0.5114493 ]
ITERATION 3: [ 0.8200011  -0.7581528   0.05420775  0.5215785 ]
ITERATION 4: [ 0.7418579  -0.65257735  0.0772266   0.5356858 ]
ITERATION 5: [ 0.6520395  -0.53165145  0.1036809   0.5545008 ]
ITERATION 6: [ 0.5504398  -0.39661855  0.1341222   0.5780387 ]
ITERATION 7: [ 0.4400395  -0.25436425  0.1688536   0.6040144 ]
ITERATION 8: [ 0.3278025 -0.118717   0.2077031  0.6276199]
ITERATION 9: [ 0.221235   -0.002998    0.24986135  0.6441514 ]
ITERATION 10: [0.1239807  0.0880478  0.29421125 0.6525841 ]
ITERATION 11: [0.0358068 0.1573263 0.3397089 0.6552114]
ITERATION 12: [-0.0445147   0.20922355  0.3855374   0.6547514 ]
ITERATION 13: [-0.118155    0.24785615  0.4309784   0.6532237 ]
ITERATION 14: [-0.1861346   0.27610965  0.4756949   0.6519735 ]
ITERATION 15: [-0.2491127   0.29619525  0.5193601   0.651532  ]
ITERATION 16: [-0.3077273   0.31005645  0.5617502   0.652113  ]
I

In [7]:
#testing model for user input
weights = [-2.8940211 , -0.1778251, 2.81203915, 1.1965985 ]
user_input = [float(input('Enter Your Input: ')) for _ in range(4)]
input_by_user = np.array(user_input)
print(input_by_user)

Enter Your Input: 1
Enter Your Input: 0
Enter Your Input: 1
Enter Your Input: 0
[1. 0. 1. 0.]


In [8]:
output = bipolar_sigmoid(np.dot(input_by_user, weights))
print(f'OUTPUT CALCULATED: {output}')

OUTPUT CALCULATED: -0.041
