In [93]:
import numpy as np

In [94]:
def signum(x):
    if x >= 0:
        return 1
    else:
        return -1

In [95]:
training_input = np.array([[1,-2,1.5,0],[1,-0.5,-2,-1.5],[0,1,-1,1.5]])
weights = np.array([1,-1,0,0.5])
print('Training Inputs:\n', training_input)
print('Initial weights:\n', weights)

Training Inputs:
 [[ 1.  -2.   1.5  0. ]
 [ 1.  -0.5 -2.  -1.5]
 [ 0.   1.  -1.   1.5]]
Initial weights:
 [ 1.  -1.   0.   0.5]


In [96]:
c = 1
for count in range(0,10): #for 10 iteration, 1 iteration weight update 3 times(3 inputs😃)
    for i in training_input:
        fnet = signum(np.dot(i,weights))
        del_w = np.dot(i, c*fnet)
        weights += del_w
    print(f'ITERATION {count}:', weights)
    

ITERATION 0: [ 1.  -3.5  4.5  0.5]
ITERATION 1: [ 1.  -6.   9.   0.5]
ITERATION 2: [ 1.  -8.5 13.5  0.5]
ITERATION 3: [  1.  -11.   18.    0.5]
ITERATION 4: [  1.  -13.5  22.5   0.5]
ITERATION 5: [  1.  -16.   27.    0.5]
ITERATION 6: [  1.  -18.5  31.5   0.5]
ITERATION 7: [  1.  -21.   36.    0.5]
ITERATION 8: [  1.  -23.5  40.5   0.5]
ITERATION 9: [  1.  -26.   45.    0.5]


In [107]:
#randomised weights
weights = np.random.rand(1, 4).round(1)
print('Random initial weight:\n', weights)
c = 1
for count in range(0,10): #for 10 iteration, 1 iteration weight update 3 times(3 inputs😃)
    for i in training_input:
        fnet = signum(np.dot(i,weights[0])) #[[]]🤔
        del_w = np.dot(i, c*fnet)
        weights += del_w
    print(f'ITERATION {count}:', weights)

Random initial weight:
 [[0.7 0.6 0.2 0.8]]
ITERATION 0: [[-1.3  4.1 -0.3  3.8]]
ITERATION 1: [[-3.3  7.6 -0.8  6.8]]
ITERATION 2: [[-5.3 11.1 -1.3  9.8]]
ITERATION 3: [[-7.3 14.6 -1.8 12.8]]
ITERATION 4: [[-9.3 18.1 -2.3 15.8]]
ITERATION 5: [[-11.3  21.6  -2.8  18.8]]
ITERATION 6: [[-13.3  25.1  -3.3  21.8]]
ITERATION 7: [[-15.3  28.6  -3.8  24.8]]
ITERATION 8: [[-17.3  32.1  -4.3  27.8]]
ITERATION 9: [[-19.3  35.6  -4.8  30.8]]
